export const products = [
  {
    id: 1,
    name: "Netflix Premium",
    category: "streaming",
    categoryLabel: "Streaming",
    description: "4K UHD\nรับประกัน 100%",
    price: 129,
    originalPrice: null,
    unit: "เดือน",
    badge: "HOT" as const,
    rating: 4.9,
    reviewCount: 5432,
    image: "/logos/netflix.svg",
    color: "#E50914",
    bgColor: "rgba(229, 9, 20, 0.15)",
    features: [
      "จัดส่งอัตโนมัติ ทันที 24 ชม.",
      "4K Ultra HD + HDR",
      "รับชมได้ 4 จอพร้อมกัน",
      "รับประกันตลอดระยะเวลา",
      "ดาวน์โหลดดูออฟไลน์",
    ],
    slug: "netflix-premium",
    variants: [
      { name: "Netflix Premium", duration: "1 เดือน", price: 129 },
      { name: "Netflix Premium", duration: "3 เดือน", price: 359 },
      { name: "Netflix 4K Ultra HD", duration: "1 เดือน", price: 159 },
      { name: "Netflix Kids", duration: "1 เดือน", price: 89 },
      { name: "Netflix 1 จอ", duration: "1 เดือน", price: 69 },
    ],
  },
  {
    id: 2,
    name: "Disney+ Premium",
    category: "streaming",
    categoryLabel: "Streaming",
    description: "4K UHD\nรับประกัน 100%",
    price: 129,
    originalPrice: null,
    unit: "เดือน",
    badge: "HOT" as const,
    rating: 4.9,
    reviewCount: 3245,
    image: "/logos/disney.svg",
    color: "#113CCF",
    bgColor: "rgba(17, 60, 207, 0.15)",
    features: [
      "จัดส่งอัตโนมัติ ทันที 24 ชม.",
      "4K Ultra HD",
      "รับชมได้ทุกอุปกรณ์",
      "รับประกันตลอดระยะเวลา",
    ],
    slug: "disney-plus-premium",
    variants: [
      { name: "Disney+ Premium", duration: "1 เดือน", price: 129 },
      { name: "Disney+ Premium", duration: "3 เดือน", price: 349 },
    ],
  },
  {
    id: 3,
    name: "Spotify Premium",
    category: "music",
    categoryLabel: "Music",
    description: "ฟังเพลงไม่จำกัด\nดาวน์โหลดได้",
    price: 69,
    originalPrice: null,
    unit: "เดือน",
    badge: "HOT" as const,
    rating: 4.8,
    reviewCount: 2154,
    image: "/logos/spotify.svg",
    color: "#1DB954",
    bgColor: "rgba(29, 185, 84, 0.15)",
    features: [
      "ฟังเพลงไม่จำกัด",
      "ไม่มีโฆษณา",
      "ดาวน์โหลดฟังออฟไลน์",
      "คุณภาพเสียงสูงสุด",
      "ข้ามเพลงได้ไม่จำกัด",
    ],
    slug: "spotify-premium",
    variants: [
      { name: "Spotify Premium", duration: "1 เดือน", price: 69 },
      { name: "Spotify Premium", duration: "3 เดือน", price: 189 },
      { name: "Spotify Premium Duo", duration: "1 เดือน", price: 89 },
      { name: "Spotify Premium Family", duration: "1 เดือน", price: 119 },
    ],
  },
  {
    id: 4,
    name: "YouTube Premium",
    category: "streaming",
    categoryLabel: "Streaming",
    description: "ไม่มีโฆษณา\nYouTube Music",
    price: 89,
    originalPrice: null,
    unit: "เดือน",
    badge: "NEW" as const,
    rating: 4.8,
    reviewCount: 3876,
    image: "/logos/youtube.svg",
    color: "#FF0000",
    bgColor: "rgba(255, 0, 0, 0.15)",
    features: [
      "ดูวิดีโอไม่มีโฆษณา",
      "YouTube Music ฟรี",
      "ดาวน์โหลดดูออฟไลน์",
      "เปิดแอปอื่นได้ขณะฟัง",
    ],
    slug: "youtube-premium",
    variants: [
      { name: "YouTube Premium", duration: "1 เดือน", price: 89 },
      { name: "YouTube Premium", duration: "3 เดือน", price: 249 },
      { name: "YouTube Premium Family", duration: "1 เดือน", price: 129 },
    ],
  },
  {
    id: 5,
    name: "Prime Video",
    category: "streaming",
    categoryLabel: "Streaming",
    description: "4K UHD\nส่งอัจฉริมิติ",
    price: 129,
    originalPrice: null,
    unit: "เดือน",
    badge: "HOT" as const,
    rating: 4.8,
    reviewCount: 1987,
    image: "/logos/prime.svg",
    color: "#00A8E1",
    bgColor: "rgba(0, 168, 225, 0.15)",
    features: [
      "4K Ultra HD",
      "Amazon Originals",
      "ดาวน์โหลดได้",
      "รับประกัน 100%",
    ],
    slug: "prime-video",
    variants: [
      { name: "Prime Video", duration: "1 เดือน", price: 129 },
      { name: "Prime Video", duration: "3 เดือน", price: 359 },
    ],
  },
  {
    id: 6,
    name: "HBO Max",
    category: "streaming",
    categoryLabel: "Streaming",
    description: "4K UHD\nรับประกัน 100%",
    price: 129,
    originalPrice: null,
    unit: "เดือน",
    badge: "NEW" as const,
    rating: 4.9,
    reviewCount: 1254,
    image: "/logos/hbo.svg",
    color: "#5822B4",
    bgColor: "rgba(88, 34, 180, 0.15)",
    features: [
      "4K Ultra HD + Dolby Atmos",
      "HBO Originals ทั้งหมด",
      "Warner Bros. Movies",
      "ดาวน์โหลดได้",
    ],
    slug: "hbo-max",
    variants: [
      { name: "HBO Max", duration: "1 เดือน", price: 129 },
      { name: "HBO Max", duration: "3 เดือน", price: 359 },
    ],
  },
  {
    id: 7,
    name: "VIU Premium",
    category: "streaming",
    categoryLabel: "Streaming",
    description: "Full HD\nซีรีส์เกาหลี",
    price: 89,
    originalPrice: 159,
    unit: "เดือน",
    badge: "HOT" as const,
    rating: 4.7,
    reviewCount: 892,
    image: "/logos/viu.svg",
    color: "#FF6B35",
    bgColor: "rgba(255, 107, 53, 0.15)",
    features: [
      "ซีรีส์เกาหลีล่าสุด",
      "Full HD",
      "ซับไทย/อังกฤษ",
      "ไม่มีโฆษณา",
    ],
    slug: "viu-premium",
    variants: [
      { name: "VIU Premium", duration: "1 เดือน", price: 89 },
    ],
  },
  {
    id: 8,
    name: "Apple TV+",
    category: "streaming",
    categoryLabel: "Streaming",
    description: "4K HDR\nApple Originals",
    price: 99,
    originalPrice: null,
    unit: "เดือน",
    badge: "NEW" as const,
    rating: 4.7,
    reviewCount: 654,
    image: "/logos/appletv.svg",
    color: "#A2AAAD",
    bgColor: "rgba(162, 170, 173, 0.15)",
    features: [
      "Apple Originals เฉพาะ",
      "4K HDR + Dolby Vision",
      "ดาวน์โหลดได้",
    ],
    slug: "apple-tv-plus",
    variants: [
      { name: "Apple TV+", duration: "1 เดือน", price: 99 },
    ],
  },
];

export const categories = [
  { id: "streaming", name: "Streaming", count: 32, icon: "📺", color: "#7C3AED" },
  { id: "music", name: "Music", count: 12, icon: "🎵", color: "#1DB954" },
  { id: "office", name: "Office", count: 18, icon: "💼", color: "#0078D4" },
  { id: "ai-tools", name: "AI Tools", count: 14, icon: "🤖", color: "#FF6B35" },
  { id: "productivity", name: "Productivity", count: 16, icon: "🚀", color: "#EC4899" },
  { id: "game", name: "Game", count: 10, icon: "🎮", color: "#F59E0B" },
];

export const reviews = [
  {
    id: 1,
    name: "Natcha",
    avatar: null,
    verified: true,
    rating: 5,
    product: "Netflix Premium",
    comment: "ซื้อ Netflix ไปใช้แล้ว งานได้จริง ส่งไวมากกก",
    timeAgo: "2 ชั่วโมงที่แล้ว",
  },
  {
    id: 2,
    name: "Kittipong",
    avatar: null,
    verified: true,
    rating: 5,
    product: "Spotify Premium",
    comment: "Spotify Premium คุ้มมากครับ ฟังเพลงได้ทุกที่ ไม่มีโฆษณา แนะนำเลย",
    timeAgo: "5 ชั่วโมงที่แล้ว",
  },
  {
    id: 3,
    name: "Jirawat",
    avatar: null,
    verified: true,
    rating: 5,
    product: "Disney+ Premium",
    comment: "บริการดีมากๆ ส่งเร็ว ราคาถูก จะกลับมาซื้อใหม่แน่นอน",
    timeAgo: "1 วันที่แล้ว",
  },
  {
    id: 4,
    name: "Somying",
    avatar: null,
    verified: true,
    rating: 5,
    product: "YouTube Premium",
    comment: "ดีมากค่ะ ส่งไว ได้รับบัญชีทันที ใช้งานได้จริง",
    timeAgo: "2 วันที่แล้ว",
  },
];

export const flashSaleProducts = [
  { ...products[4], discountPercent: 30 },
  { ...products[5], discountPercent: 25 },
  { ...products[6], discountPercent: 40 },
  { ...products[7], discountPercent: 20 },
];

export const features = [
  {
    icon: "⚡",
    title: "ส่งไว ภายใน 1 นาที",
    description: "ระบบอัตโนมัติ ทำรายการสำเร็จ รับบัญชีที่ไม่ต้องรอนาน",
  },
  {
    icon: "🔒",
    title: "ปลอดภัย 100%",
    description: "ข้อมูลไร้วิไล ไม่เก็บข้อมูลลูกค้า มั่นใจได้ในความปลอดภัย",
  },
  {
    icon: "💳",
    title: "ชำระเงินง่าย",
    description: "รองรับทุกช่องทางการชำระเงิน QR Code, บัตรเครดิต, พร้อมเพย์",
  },
  {
    icon: "🎁",
    title: "โปรโมชั่นทุกวัน",
    description: "อัปเดตโปรโมชั่นใหม่ทุกวัน คุ้มค่าทุกการสั่งซื้อ",
  },
];

export const paymentMethods = [
  { name: "QR Code", icon: "qr" },
  { name: "VISA", icon: "visa" },
  { name: "Mastercard", icon: "mastercard" },
  { name: "TrueMoney", icon: "truemoney" },
  { name: "LINE Pay", icon: "linepay" },
];

export const stats = {
  totalCustomers: "10,248+",
  rating: "4.9/5",
  reviews: "10,248 รีวิว",
  successRate: "99.9%",
};
